# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'TravelBro' do
pod 'Firebase', '>= 2.5.1'

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.1'
pod 'GoogleMaps'

pod 'BTNavigationDropdownMenu'

end

target 'TravelBroTests' do

end

target 'TravelBroUITests' do

end

